wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.2
architecture:
  desc: null
  value: CNN
dataset_id:
  desc: null
  value: peds-0192
infra:
  desc: null
  value: AWS
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.14.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687396928.425389
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.9.13
      5: 0.14.2
      8:
      - 3
      - 5
